### ISSUE TITLE
Missing event attributes compared to analytics-android

### ISSUE THREAD

**Issue by napas-pomelo** [segmentio/analytics-kotlin#113]
**Describe the bug**
Missing attributes for event tracking compared to [analytics-android](https://github.com/segmentio/analytics-android) lib.
The crucial ones are `device.advertisingId` and `traits`
However, `triaits` only appears when calling `identify(...)` but not when calling `track(...)` function

```
{
  "context": {
    "device": {
      "adTrackingEnabled": true,
      "advertisingId": "xxx",
      ...
    },
    "traits": {
      "email": "xxxxx",
      "first_name": "xxxx",
      ...
    },
    ...
  },
  ...
}
```

**To Reproduce**
1. Call identify with traits `analytics.identify(userId = ..., traits = ...)`
2. Call `analytics.track(...)`
3. Check Segment sources debugger

**Expected behavior**
analytics-kotlin should send the same attributes as analytics-android does

**Platform (please complete the following information):**
 - com.segment.analytics.kotlin:android:1.9.0
 - com.segment.analytics.android:analytics:4.10.4

**Comment by wenxi-zeng** [comment]
hey @napas-pomelo, we no longer append traits to the track call since some destinations has PII constraints on that data. however, you can append the data by yourself with a simple plugin like below:
```
class TraitsPlugin: EventPlugin {
    override val type: Plugin.Type = Plugin.Type.Enrichment
    override lateinit var analytics: Analytics
    private lateinit var traits: Traits

    override fun track(payload: TrackEvent): BaseEvent? {
        val event = super.track(payload)

        if (event is TrackEvent) {
            event.context = updateJsonObject(event.context) {
                it["traits"] = traits
            }
        }

        return event
    }

    override fun identify(payload: IdentifyEvent): BaseEvent? {
        traits = payload.traits
        return super.identify(payload)
    }
}
```
in terms of advertisingId, we have a [sample plugin](https://github.com/segmentio/analytics-kotlin/blob/main/samples/kotlin-android-app/src/main/java/com/segment/analytics/next/plugins/AndroidAdvertisingIdPlugin.kt) provided for you to use. you can grab it as is or customize it according to your needs. all you need to do is to call `analytics.add` to add these plugins. the event will flow with the attributes you want.

**Comment by empowerHamish** [comment]
Should this be flagged in the [Upgrade notes](https://segment.com/docs/connections/sources/catalog/libraries/mobile/kotlin-android/migration/#4-upgrade-notes-changes-to-the-configuration-object)? This one caught us out as it was an unexpected/undocumented change in behaviour from Analytics-Android and we didn't notice for a while

**Comment by wenxi-zeng** [comment]
hi @empowerHamish that's a good call out. will add it to the upgrade notes. thanks for bring this to our attention
