### ISSUE TITLE
Migration from old SDK is blocked as default methods don't support adding of integration options

### ISSUE THREAD

**Issue by amal** [segmentio/analytics-kotlin#160]
With previous SDK we used to make calls like this:
```kotlin
analytics.reset()
val traits = Traits()
val intercomOptions = HashMap<String, Any>()
intercomOptions["userHash"] = hash
val options = Options().setIntegrationOptions("Intercom", intercomOptions)
analytics.identify(userId, traits, options)
```

Now it's not possible to pass integration options in any way.
`analytics.identify` has no parameter for `options`.

`analytics.process()` could be used, but it's not a full equivalent of `identify`.

Please provide the possibility to fully customize events as it was possible before with `Options`.

**Comment by wenxi-zeng** [comment]
hey @amal, this library still has this capability, in a more flexible way. you can write a plugin like the following the achieve what you want:
```kotlin
class IntegrationOptionPlugin : EventPlugin {
    override val type = Plugin.Type.Enrichment
    override lateinit var analytics: Analytics

    override fun identify(payload: IdentifyEvent): BaseEvent? {
        payload.integrations = updateJsonObject(payload.integrations) {
            it["Intercom"] = buildJsonObject {
                // YOUR INTERCOM OPTIONS
            }
        }
        return super.identify(payload)
    }
}
```
and then add it to analytics:
```kotlin
analytics.add(IntegrationOptionPlugin())
```

the above plugin updates the same option for all identify events (you can do the same for all other events), but if you wanna attach different option to different events, you can still do it in the following way:
```kotlin
class IntegrationOptionPerEventPlugin : EventPlugin {
    override val type = Plugin.Type.Enrichment
    override lateinit var analytics: Analytics

    override fun identify(payload: IdentifyEvent): BaseEvent? {
        payload.traits["Intercom"]?.let { intercom ->
            payload.integrations = updateJsonObject(payload.integrations) { integrations ->
                integrations["Intercom"] = intercom
            }

            payload.traits = updateJsonObject(payload.traits) {
                it.remove("Intercom")
            }
        }
        
        return super.identify(payload)
    }
}
```
add it to analytics and identify in the following way:
```kotlin
analytics.add(IntegrationOptionPerEventPlugin())
analytics.identify("userId", buildJsonObject {
    put("Intercom", buildJsonObject {
        // YOUR INTERCOM OPTIONS
    })
})
```

**Comment by amal** [comment]
Sorry, but this seems like a mega overkill for the simple provided case. Not practical and not brief at all.

**Comment by bsneed** [comment]
You'd rather include the same or similar set of options at every call point instead??

**Comment by wenxi-zeng** [comment]
hey @amal can you explain a bit more on why is it not practical? if you use option 1, all you need to do is 
```
analytics.identify(userId, traits)
```
you don't need to pass options for every call, which actually is more practical and simpler.
if you use option 2, it's just the as complex as what you currently do:
```
var options = buildJsonObject {}
analytics.identify("userId", buildJsonObject {
    put("Intercom", traits, options)
})
```
the only difference is the setup. the old SDK hardcode the setup for you, whereas now you have the option to customize, and you only need to set it up once. this is also not an overkill, since not every app needs this feature, the current architecture actually keeps the SDK small by allowing user dynamically adding things per need. imagining you would have to raise a similar feature request to analytics-android, you would have to wait for a release cycle from us, whereas now you can just copy/paste the plugin provided in the previous comment and solve your need.
note that everything comes with a tradeoff. yes, we are trading off this specific feature with flexibility. but believe me, the pros are more than cons.

**Comment by amal** [comment]
For me, it seems impractical as:
1) Clearly more code to achieve the same tiny goal.
2) `EventPlugin` s a completely additional entity that lies far from my simple goal of passing one additional value with one specific call. It makes no sense unless only to satisfy the requirements of lib and nothing else. Which seems like a bad API design to me.

Plugin maybe provides more flexibility. But I don't need any of it. So, why do things less convenient than they already were? )
