### ISSUE TITLE
Segment settings are not updated

### ISSUE THREAD

**Issue by peterplamenovpenchev** [segmentio/analytics-kotlin#97]
**Describe the bug**
Analytics settings are not updating

**To Reproduce**
1. Create an Android source in Segment's web app
2. Add a destination
3. In the mobile app integrate with that destination (usually the destination's dev provides a segment integrated library)

**Observed behavior**
The newly added destination is not returned by `https://cdn-settings.segment.com/v1/projects/$writeKey/settings`.
If I make additional changes of the Android source in Segment's web app (e.g. delete a destination) its values are still returned too.

**Expected behavior**
The newly added destination & its settings should be returned by `https://cdn-settings.segment.com/v1/projects/$writeKey/settings`

**Platform:**
 - Library Version in use: `1.7.0`
 - Platform being tested: Android

**Comment by wenxi-zeng** [comment]
hey @peterplamenovpenchev, thanks for bring this to our attention. looks like the cdn server is not reflecting the changes. we're looking into this.

**Comment by wenxi-zeng** [comment]
got a response from the team. the cdn server can take up to a day to reflect the changes. sometimes if you request it enough times it will get cached and then you will have to wait for the cache to expire. closing out this issue since this is normal. feel free to reopen it if your issue still persists.

**Comment by peterplamenovpenchev** [comment]
Thanks @wenxi-zeng.
